import test from 'node:test';
import assert from 'node:assert/strict';
import {IDBFactory} from 'fake-indexeddb';
import {createModelCache} from '../../../web/static/model-download.js';
const origin='http://cache.test';
const url=n=>`${origin}/api/assets/characters/chr_${n}/file/versions/v001/model.glb`;
function glb(marker=1){const b=new ArrayBuffer(32),v=new DataView(b);v.setUint32(0,0x46546c67,true);v.setUint32(4,2,true);v.setUint32(8,32,true);v.setUint32(12,12,true);v.setUint32(16,0x4e4f534a,true);new Uint8Array(b,20).set(new TextEncoder().encode('{"asset":{}}'));new Uint8Array(b)[31]=marker;return b;}
function fixture(options={}){let etag='a',data=glb(),status=200;const calls=[];const idb=new IDBFactory();const config={idb,baseURL:origin,...options,fetcher:async(u,o={})=>{calls.push(u);if(o.signal?.aborted)throw new DOMException('Cancelled','AbortError');if(u.endsWith('model-cache'))return new Response(JSON.stringify({etag,size:data.byteLength}),{status});return new Response(data.slice(0));}};return {calls,make:()=>createModelCache(config),replace:(e,b)=>{etag=e;data=b;},status:s=>status=s};}
test('opening alone does not prefetch; memory cache survives consumer buffer changes',async()=>{const f=fixture(),c=f.make();assert.equal(f.calls.length,0);let p;const a=await c.bytes(url(1));new Uint8Array(a)[31]=99;const b=await c.bytes(url(1),null,e=>p=e);assert.equal(new Uint8Array(b)[31],1);assert.equal(p.cache,'memory');assert.equal(f.calls.filter(u=>u.endsWith('.glb')).length,1);await c.flush();});
test('new page/cache instance reuses IndexedDB, with version validation',async()=>{const f=fixture(),c=f.make();await c.bytes(url(1));await c.flush();let p;await f.make().bytes(url(1),null,e=>p=e);assert.equal(p.cache,'disk');assert.equal(f.calls.filter(u=>u.endsWith('.glb')).length,1);});
test('same version overwritten upstream invalidates disk and memory',async()=>{const f=fixture(),c=f.make();await c.bytes(url(1));await c.flush();f.replace('b',glb(2));const b=await c.bytes(url(1));assert.equal(new Uint8Array(b)[31],2);await c.flush();let p;await f.make().bytes(url(1),null,e=>p=e);assert.equal(p.cache,'disk');assert.equal(f.calls.filter(u=>u.endsWith('.glb')).length,2);});
test('authorization/deletion failure does not return cached private bytes',async()=>{const f=fixture(),c=f.make();await c.bytes(url(1));await c.flush();f.status(403);await assert.rejects(c.bytes(url(1)),/403/);f.status(200);await c.bytes(url(1));assert.equal(f.calls.filter(u=>u.endsWith('.glb')).length,2);});
test('disk LRU evicts oldest entries only when budget is exceeded',async()=>{const f=fixture({memoryLimit:0,diskLimit:64}),c=f.make();await c.bytes(url(1));await c.bytes(url(2));await c.flush();await c.bytes(url(1));await c.flush();await new Promise(r=>setTimeout(r,2));await c.bytes(url(3));await c.flush();let p;await f.make().bytes(url(1),null,e=>p=e);assert.equal(p.cache,'disk');await f.make().bytes(url(2),null,e=>p=e);assert.equal(p.cache,null);});
test('cancelled and truncated loads are never cached',async()=>{const f=fixture(),c=f.make(),abort=new AbortController();abort.abort();await assert.rejects(c.bytes(url(1),abort.signal),{name:'AbortError'});assert.equal(f.calls.length,0);f.replace('bad',new ArrayBuffer(20));await assert.rejects(c.bytes(url(1)),/GLB/);f.replace('good',glb());await c.bytes(url(1));assert.equal(f.calls.filter(u=>u.endsWith('.glb')).length,2);});
test('unavailable IndexedDB degrades to memory without failing model load',async()=>{const f=fixture({idb:{open(){throw Error('storage denied');}}}),c=f.make();await c.bytes(url(1));await c.flush();await c.bytes(url(1));assert.equal(f.calls.filter(u=>u.endsWith('.glb')).length,1);});
